INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES (10001, 'andrew', 'Learn JPA', CURRENT_TIMESTAMP(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES (10002, 'andrew', 'Learn AWS', CURRENT_TIMESTAMP(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES (10003, 'andrew', 'Learn Full Stack Development', CURRENT_TIMESTAMP(), false);